version: '3.4'

services:
  businesscardpuzzle:
    # depends_on: 
      # - syslogserver
    # networks: 
    #   - container_bridge
    container_name: businesscardpuzzle
    image: wisehackermonkey/businesscardpuzzle:latest
    environment:
      NODE_ENV: production
    ports:
      - 3333:3000
    restart: always
