version: '3.4'

services:
  businesscardpuzzle:
    # depends_on: 
      # - syslogserver
    # networks: 
    #   - container_bridge
    container_name: businesscardpuzzle
    env_file: 
      - .env
    image: wisehackermonkey/businesscardpuzzle:latest
    environment:
      NODE_ENV: production
    ports:
      - 3333:3000
    restart: always
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://172.31.0.2:514"
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-address: 'tcp://syslogserver:514'

#   syslogserver:
  
#       restart: always
#       env_file: 
#         - .env
      
#       ports:
#           - '8080:80'
#           - '514:514/udp'
#       image: pbertera/syslogserver
# networks: 
#   container_bridge:
#     driver: bridge 

      # - "traefik.enable=true"
      # - "traefik.http.routers.businesscardpuzzle.rule=Path(`/puzzle`)"
  # syslogserver: 

  #   build:
  #     context: .
  #     dockerfile: Dockerfile.logger
  #   hostname: syslog 
  #   container_name: syslog 
  #   restart: always
  #   volumes: 
  #     - "/var/log:/var/log" 
  #   ports: 
  #     - 514:514
  #     - 514:514/udp
  #   cap_add:
  #     - SYSLOG