version: '3.4'

services:
  businesscardpuzzle:
    image: businesscardpuzzle
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
