version: '3.4'

services:
  businesscardpuzzle:
    env_file: 
      - .env
    image: wisehackermonkey/businesscardpuzzle:latest
    environment:
      NODE_ENV: production
    ports:
      - 3333:3000
    restart: always